### ISSUE TITLE
使用www.visa.com.sg作为唯一的proxyIP，无法访问CF类网站

### ISSUE THREAD

**Issue by AugustRothschild** [yonggekkk/Cloudflare_vless_trojan#101]
大佬，我用你的workers-trojan代码部署节点，使用www.visa.com.sg作为唯一的proxyIP，使用V2RayU，这个节点可以看油管，但是无法访问CF类网站，如Cloudflare网站、ww.visa.com.sg等等。此外，将节点二维码分享至小火箭，有延迟，但网络不通。我更改的代码     const proxyIPs = ["www.visa.com.sg"];     请问是哪里出错了呢？谢谢🙏

**Comment by yonggekkk** [comment]
www.visa.com.sg并不能做proxyIP，代码默认其他大佬的Proxyip的就可以用，不用做任何修改

**Comment by AugustRothschild** [comment]
> www.visa.com.sg并不能做proxyIP，代码默认其他大佬的Proxyip的就可以用，不用做任何修改

考虑到用其他大佬的proxyip后ip在全球跳，想用这么一个域名proxyip把IP固定在一个国家用，填客户端的地址ip失效得太快了。请问大佬，不采用优选IP地址填客户端（因为失效太快）的话，有办法把IP固定在一个国家吗？

**Comment by yonggekkk** [comment]
先搞清楚proxyip的作用吧！
至于固定国家IP，客户端任意一个优选IP或者大厂公共域名就可以固定国家

**Comment by AugustRothschild** [comment]
> 先搞清楚proxyip的作用吧！
> 
> 至于固定国家IP，客户端地址写上一个优选IP或者大厂公共CDN域名就可以固定国家

👌，谢谢大佬。客户端分享trojan二维码给小火箭，小火箭有延迟但网络不通，请大佬关注一下呀。🙏

**Comment by yonggekkk** [comment]
> > 先搞清楚proxyip的作用吧！
> > 至于固定国家IP，客户端地址写上一个优选IP或者大厂公共CDN域名就可以固定国家
> 
> 👌，谢谢大佬。客户端分享trojan二维码给小火箭，小火箭有延迟但网络不通，请大佬关注一下呀。🙏

参考https://youtu.be/lmhhL8M1k0I

**Comment by louielove** [comment]
我用ts.hpc.tw也不能登入CF的网站和CF类的网站,这是怎么回事,换有一个行不行,不用proxyip也不能登入CF类的网站,有解决办法吗??

**Comment by louielove** [comment]
> > > nat64版本的是什么，我是小白，全程跟着你的视频部署的，这个是proxyip还是什么，如果是proxyip，能不能给我个可以用的proxyip地址，我直接变量里改一下，谢谢大佬
> > 
> > 
> > https://github.com/yonggekkk/Cloudflare_vless_trojan/tree/main/Vless_workers_pages
> 
> 好的弄好了，谢谢大佬.这个现在也不知道ip1到ip7，只有ip8到ip13了

打错的了不是不知道,是不支持IP1到IP7
