### ISSUE TITLE
pages部署后无法使用

### ISSUE THREAD

**Issue by juingtin** [yonggekkk/Cloudflare_vless_trojan#102]
RT
用pages.dev和自定义域都打不开，找不到页面。
v2ray里直接订阅也无效。

**Comment by yonggekkk** [comment]
发图

**Comment by flame9468** [comment]
找不到 05yg.pages.dev 的网页找不到与以下网址对应的网页：https://05yg.pages.dev/33997a20-93ae-4884-9fd5-ad43ba554ca4
HTTP ERROR 404

**Comment by flame9468** [comment]
HTTP ERROR 404

**Comment by flame9468** [comment]
找出问题了，不能修改js文件名
