### ISSUE TITLE
可以添加功能实现所有流量都走反代ip吗

### ISSUE THREAD

**Issue by xxntmctx** [yonggekkk/Cloudflare_vless_trojan#119]
我在proxyip设置了单个反代域名，但是代理开全局访问itdog.cn测试ip全是cloudflare官方ip,只有访问cloudflare的域名才显示反代ip
![QQ_1721729616425](https://github.com/user-attachments/assets/cba432f9-8a0f-46a3-9381-9b6c55efc76b)

**Comment by yonggekkk** [comment]
CF vless/trojan永久免费节点教程（四）：解读优选官方IP、优选反代IP、优选域名三者的关系与特点；ProxyIP存在的意义
https://youtu.be/NaLd-orwFUE

**Comment by yonggekkk** [comment]
Cf类网站只走proxyip

**Comment by xxntmctx** [comment]
> Cf类网站只走proxyip

感谢大佬回复，我是想非cf类的网站也走proxyip

**Comment by yonggekkk** [comment]
> > Cf类网站只走proxyip
> 
> 感谢大佬回复，我是想非cf类的网站也走proxyip

除非你是cf老板

**Comment by xxntmctx** [comment]
我找了很久没看到类似问题答案，为什么非cf类的网站不能也走proxyip呀，能具体说说吗

**Comment by yonggekkk** [comment]
Cf官方设定
