### ISSUE TITLE
在客户端上的path设置处直接修改：/pyip=IPV4地址   后，IP地址似乎与设备相绑定，删除该节点后换用其他节点，ip.sb依旧显示前序IPV4的地址。

### ISSUE THREAD

**Issue by AugustRothschild** [yonggekkk/Cloudflare_vless_trojan#121]
如题，几个节点共存，修改其中一个节点的path设置为/pyip=IPV4地址，切换其他节点后，ip.sb依旧显示所设置的IPV4地址；删除该节点换用其他节点后，ip.sb依旧显示前序IPV4地址；只有将其他节点的path设置为/pyip=其他IPV4地址后，ip.sb才会显示其他IPV4地址。似乎path设置为/pyip=IPV4地址后能够与设备相绑定。大佬，这个情况正常吗？虽然能够固定IP，但感觉不是很安全。

**Comment by yonggekkk** [comment]
1：看下项目说明第三点"注意"后面的话
2：proxyip仅仅只能固定cf网站的ip
有些概念性的东西你没搞清楚哦

**Comment by AugustRothschild** [comment]
大佬，我修改其中一个节点的path设置为/pyip=IPV4地址后，删除了客户端中的所有地址，然后重新导入了节点，这次path路径为默认的2560，但是在ip.sb或者在https://ipaddress.my/中依旧显示是之前设置的IPV4地址，请问这正常吗？有安全隐患吗？感谢解答！

**Comment by yonggekkk** [comment]
默认2560就是用设置好的全局proxyip！！
不知安全隐患是啥？都不是你的东西呀

**Comment by AugustRothschild** [comment]
我的意思是删除客户端中所有的节点后重新导入节点，默认path路径没动，ip.sb依旧显示之前设置的IPV4地址。按理说IP地址应该跳动，但不知为什么新节点依旧显示之前设置过的ipv4地址，所以很疑惑。
