### ISSUE TITLE
自定义uuid后节点失效

### ISSUE THREAD

**Issue by mario-huang** [yonggekkk/Cloudflare_vless_trojan#122]
甬哥好。我使用pages+vless部署。什么都不改的情况下，sb订阅成功，节点都是通的。但是我在pages里面自定义环境变量uuid之后（确认过uuid格式正确且有效），sb的订阅文件里看到了自定义的uuid，但是这份订阅在sb里节点都是不通的。切换回原来的默认的uuid，也是不通。就是说works里面的uuid没用了，自定义的也没用。删除自定义环境变量uuid之后，重新订阅，恢复正常。

**Comment by yonggekkk** [comment]
视频有说pages每次变量更新要重新上传一份

**Comment by mario-huang** [comment]
> 视频有说pages每次变量更新要重新上传一份

好的大佬，我以为重新部署就相当于重新上传了。我再测试一下哈。

**Comment by mario-huang** [comment]
嗯。。。也许是因为我没有直接按照视频里的，直接上传资产。我是fork之后，通过git部署的。先设置了变量uuid和根目录Vless_workers_pages，再开始部署。这种情况设置了uuid就不行，不设置就ok。

**Comment by mario-huang** [comment]
我的锅。在第三方的网页生成的uuid，看来是无效的，但是js没有报错。后来用windows跑guid命令生成的就有效。
是不是可以把读取uuid的逻辑提前，让isValidUUID()也判断到变量uuid。
`
let userID = "77a571fb-4fd2-4b37-8596-1b7d9728bb5c";
`
改成
`
const userID = env.uuid || "77a571fb-4fd2-4b37-8596-1b7d9728bb5c";
`

**Comment by yonggekkk** [comment]
目前没有处理过git方式，需要自己设置了。
