### ISSUE TITLE
IP address remains the same

### ISSUE THREAD

**Issue by X-49** [yonggekkk/Cloudflare_vless_trojan#126]
When connecting, it shows the Cloudflare US IP address, but the actual IP address is still the same as my Russian one. I can access chatgpt.com somehow, but aistudio.google.com doesn't let me in, and in the web version of Steam the region is still defined as Russia. And this happens with many sites.

Is this the way it is supposed to work? It seemed to me that it should work as a full-fledged VPN.

**Comment by yonggekkk** [comment]
You are right, this is how this kind of proxy behaves
