### ISSUE TITLE
手机端 nekobox,v2rayng 无法使用

### ISSUE THREAD

**Issue by cgbb0** [yonggekkk/Cloudflare_vless_trojan#128]
在电脑端的v2rayn和openwrt的passwall都可以正常使用，
但是在手机上无论是v2rayng还是nekobox都不行，vless和trojan都试了。
而且一旦打开代理后，非代理的网站也都打不开了，浏览器显示net::ERR_NAME_NOT_RESOLVED,只有手机这样，其他平台都正常

**Comment by yonggekkk** [comment]
相关客户端教程稍后更新

**Comment by yesky84** [comment]
手机v2rayng客户端连接节点后需要等一下，一般1分钟左右才能通。如果不行修改一下dns设置里的VPN DNS为8.8.8.8，但连接节点后还是需要耐心等待一下。
