### ISSUE TITLE
能加个默认执行么，一键生成不需要手动操作。

### ISSUE THREAD

**Issue by star8618** [yonggekkk/Cloudflare_vless_trojan#131]
能加个默认执行么，一键生成不需要手动操作。或者用py写个，自带命令的。比如-ip v4  -sp http://xxxx  -txt ok.txt
-ip是指扫描ipv4还是ipv6，如果写上v4就是扫描ipv4
-sp 测速,用户自定义测速地址，如果不写-sp，默认的测速地址，-sp 0就不测速
-txt 完成后的地址保存到ok.txt地址中

**Comment by yonggekkk** [comment]
你都这样说了，你完全可以自已手搓运行代码啦！
