### ISSUE TITLE
proxyIP 打不开

### ISSUE THREAD

**Issue by kut2tjjj** [yonggekkk/Cloudflare_vless_trojan#135]
ProxyIP.txt文件里的网站
直连和代理都打不开:
proxy.xxxxxxxx.tk
ts.hpc.tw

直连打不开,挂代理显示 Error 1000  DNS points to prohibited IP
edgetunnel.anycast.eu.org
bestproxy.onecf.eu.org
cdn.xn--b6gac.eu.org

**Comment by yonggekkk** [comment]
这些是proxyip专用的，别放在客户端地址上
