### ISSUE TITLE
请大佬增加SOCKS5反代功能，大佬牛，大佬就是神

### ISSUE THREAD

**Issue by qqwuyucheng** [yonggekkk/Cloudflare_vless_trojan#136]
可否请大佬增加SOCKS5反代功能，方便小弟们使用自己的SOCKS5节点反代

**Comment by yonggekkk** [comment]
本周出教程

**Comment by qqwuyucheng** [comment]
感谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月21日(周三) 晚上8:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yonggekkk/Cloudflare_vless_trojan] 请大佬增加SOCKS5反代功能，大佬牛，大佬就是神 (Issue #136)




 
本周出教程

**Comment by yonggekkk** [comment]
> 感谢大佬
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月21日(周三) 晚上8:59 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yonggekkk/Cloudflare_vless_trojan] 请大佬增加SOCKS5反代功能，大佬牛，大佬就是神 (Issue #136) 本周出教程 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

CF vless/trojan永久免费节点最终教程（七）：全网独家演示真正的 "固定IP"，解决twitch.tv、chatgpt客户端报错问题；一键reality协议自制反代IP与ProxyIP
https://youtu.be/QOnMVULADko
