### ISSUE TITLE
error when using curl in you code

### ISSUE THREAD

**Issue by nickjp44** [yonggekkk/Cloudflare_vless_trojan#141]
**hi ,
when i try to use your code for finding reverse proxy Ip i get this error in my terminal , please help me to fix this :
curl -sSL https://gitlab.com/rwkgyg/CFwarp/raw/main/point/cfip.sh -o cfip.sh && chmod +x cfip.sh && bash cfip.sh
the error in the terminal:
下载更新反代IP库txt.zip文件……
下载成功
反代IP库txt.zip文件下载失败，请重置清理再次运行**

**Comment by yonggekkk** [comment]
你的网络无法连通eu.org域名吗？那就用官方IP模式吧

**Comment by nickjp44** [comment]
no everything works fine , but for using website behind cdn like chat gpt it needs reverse ip , the proxy domain you provided in your worker code , most of the time does not work in my area so i need to find revers proxy ips using the code you provided , but recently your code give me the error in the terminal

**Comment by yonggekkk** [comment]
reverse ip：zip.baipiao.eu.org

**Comment by nickjp44** [comment]
brother i click on you link and give me txt zip file but my pc does not allow me to download that ? 
is this link broken or it is my antivirus ?

**Comment by yonggekkk** [comment]
说明你的网络不支持这个下载

**Comment by nickjp44** [comment]
okey then it means nothing i can do as long as i cant download this file ,
thanks for your help

**Comment by nickjp44** [comment]
okey then it means nothing i can do as long as i cant download this file ,
thanks for your help
