### ISSUE TITLE
求救甬哥

### ISSUE THREAD

**Issue by Halecoder** [yonggekkk/Cloudflare_vless_trojan#142]
2024/09/14 20:24:13 [Error] transport/internet/websocket: failed to dial to whatismyipaddress.com:8443 > io: read/write on closed pipe

优选了很多ip和换了所有端口都是这样，不知为啥，持续几个星期了😭

**Comment by yonggekkk** [comment]
换优选IP。换客户端试试。。关键是能不能打开外网

**Comment by Halecoder** [comment]
> 换优选IP。换客户端试试。。关键是能不能打开外网

我再试试(*^_^*)，感谢🙇‍甬哥大大回复
