### ISSUE TITLE
workers trojan部署后google，youtube都用不到可是Tg，FB，Instagram都可以用

### ISSUE THREAD

**Issue by james986g** [yonggekkk/Cloudflare_vless_trojan#147]
workers的报错如下：

 "exceptions": [
    {
      "name": "Error",
      "message": "Network connection lost.",
      "timestamp": 1726908883157
    }
  ],
  "logs": [
    {
      "message": [
        "[:443--0.17223786064974833 tcp] readableStream was canceled, due to Error: unsupported command, only TCP (CONNECT) is allowed",
        ""
      ],
      "level": "log",
      "timestamp": 1726908883079
    },
    {
      "message": [
        "[:443--0.17223786064974833 tcp] readableWebSocketStream pipeTo error",
        "Error: unsupported command, only TCP (CONNECT) is allowed"
      ],
      "level": "log",
      "timestamp": 1726908883079
    }

**Comment by yonggekkk** [comment]
按视频教程部署
