### ISSUE TITLE
大佬，希望最新的代码能够支持在CF里使用pages连接Github、通过修改变量的形式来一键部署，这样方便又快捷，还方便更新代码。

### ISSUE THREAD

**Issue by AugustRothschild** [yonggekkk/Cloudflare_vless_trojan#152]
大佬，希望最新的代码能够支持在CF里使用pages连接Github、通过修改变量的形式来一键部署，这样方便又快捷，还方便更新代码。我尝试了大佬你的works来部署加了自定义域名的vless节点，也尝试过cm的edgetunnel，我发现大佬你的代码在打开一些客户端的时候不会显示SSL错误，但是CM的就会一直显示SSL错误、无法连接，想来是大佬你的代码构建的节点更安全一些。当然了，大佬，你的节点配置起来需要手动修改的地方还是很多的，相比起来还是pages连接GitHub的方式更省心。

**Comment by yonggekkk** [comment]
目前不打算github在线部署，但欢迎pr！目前代码也是支持变量的，见项目说明！

**Comment by akqzx** [comment]
fork之后用Actions，修改代码之后可以自动同步到cloudflare
