### ISSUE TITLE
win11专业版打不开呢

### ISSUE THREAD

**Issue by tjbzyl1212** [yonggekkk/Cloudflare_vless_trojan#156]
如题

**Comment by yonggekkk** [comment]
形象地描述下

**Comment by ajian1984** [comment]
运行出错 V4 V6都出错。
![微信截图_20241114235444](https://github.com/user-attachments/assets/97879d9c-3561-49f4-8139-d0cf23f8bdba)

**Comment by yonggekkk** [comment]
网络环境问题吧，没跑成功

**Comment by zwdnwlm** [comment]
The system cannot write to the specified device.
  win7  下面提示这个错误
![Uploading ab5c09e741b335d4ff84b8e206b47d5.jpg…]()

**Comment by zwdnwlm** [comment]
![ab5c09e741b335d4ff84b8e206b47d5](https://github.com/user-attachments/assets/77391a23-610e-497e-ab75-7b3596838a98)

win7下提示这个错误：The system cannot write to the specified device.

**Comment by yonggekkk** [comment]
不支持WIN7。WIN10以上

**Comment by ajian1984** [comment]
> 网络环境问题吧，没跑成功

知道哪里问题了，360杀毒

**Comment by tjbzyl1212** [comment]
win11用powershell可以运行。
