### ISSUE TITLE
Error 1101 Ray ID: 8e6d89e5f9f9ef79 • 2024-11-23 01:55:43 UTC Worker threw exception

### ISSUE THREAD

**Issue by neozhu** [yonggekkk/Cloudflare_vless_trojan#159]
The preview is working.
![image](https://github.com/user-attachments/assets/f6447792-4209-411c-a534-6f4c94baf315)
I received an error 1101 when trying to access the deployment URL.
![image](https://github.com/user-attachments/assets/4e0922ad-8ec6-44e0-8415-667ccea49fb3)

**Comment by yonggekkk** [comment]
Delete the original project, create a new one, and copy the latest code

**Comment by neozhu** [comment]
> Delete the original project, create a new one, and copy the latest code
report dangerous site this time 
![image](https://github.com/user-attachments/assets/7f037cb2-0144-4084-a1f3-1470e96953fa)

I am trying to bind a custom domain, which is also set up in Cloudflare. working fine in the preview window.
![image](https://github.com/user-attachments/assets/b2999f1c-0eee-42a7-9c58-49eb1e106050)
in browser return connection timed out
![image](https://github.com/user-attachments/assets/8a656e09-7fdd-4656-8068-d97b64648629)

**Comment by yonggekkk** [comment]
Let me check it

**Comment by neozhu** [comment]
trojan 版本有问题，vless 可以用

**Comment by neozhu** [comment]
试过了几次，trojan代码不行，vless可以，但是 vless 就算开启分片 手机端依然无法连接 worker.dev域名，我用自己的域名现在手机端可以了 用karing 客户端

**Comment by yonggekkk** [comment]
> 试过了几次，trojan代码不行，vless可以，但是 vless 就算开启分片 手机端依然无法连接 worker.dev域名，我用自己的域名现在手机端可以了 用karing 客户端

trojan 报错1101？

**Comment by neozhu** [comment]
> > 试过了几次，trojan代码不行，vless可以，但是 vless 就算开启分片 手机端依然无法连接 worker.dev域名，我用自己的域名现在手机端可以了 用karing 客户端
> 
> trojan 报错1101？

是的，

**Comment by yonggekkk** [comment]
> > > 试过了几次，trojan代码不行，vless可以，但是 vless 就算开启分片 手机端依然无法连接 worker.dev域名，我用自己的域名现在手机端可以了 用karing 客户端
> > 
> > 
> > trojan 报错1101？
> 
> 是的，

用我现在更新后的代码，还这样？

**Comment by neozhu** [comment]
从 main 分支下获取的代码，上周更新的版本 有问题, vless 还是上个月代码反而是可以的。

**Comment by eoneqiu** [comment]
fb86275版本的vless worker，遇到同样的问题

**Comment by eoneqiu** [comment]
> fb86275版本的vless worker，遇到同样的问题

重新部署又正常了

**Comment by yonggekkk** [comment]
已修复，新建项目，重新复制代码
