### ISSUE TITLE
trojan失效了

### ISSUE THREAD

**Issue by jyuan15** [yonggekkk/Cloudflare_vless_trojan#160]
4个月前部署的trojan节点，虽然在clashmeta不能用，但在v2rayN&G上都能使用，这就够了。但今天突然不通了，排除客户端反代ip原因后，删除CF上该项目，用最新代码重新部署，遗憾的是仍然不能用。以“官方域名/密码”和“自定义域名/密码”访问，得到如下结果
![2024-11-23_205343](https://github.com/user-attachments/assets/7e96d39b-7ff1-4864-81d5-40f4cd5142d7)
![2024-11-23_205249](https://github.com/user-attachments/assets/5313e950-cef1-4975-a185-310295b20477)

请甬哥大佬看看怎么回事，感谢~

**Comment by yonggekkk** [comment]
已修复，重新复制代码
