### ISSUE TITLE
page部署，出错

### ISSUE THREAD

**Issue by wbychris** [yonggekkk/Cloudflare_vless_trojan#165]
访问 https://[yg.w***s1.us.kg](https://yg.w***s1.us.kg/)/

出错信息如下：

找不到此 yg.w***s1.us.kg 页面
找不到 Web 地址对应的网页: https://yg.w***s1.us.kg/
HTTP ERROR 404

**Comment by yonggekkk** [comment]
等3分钟

**Comment by wbychris** [comment]
试了还是不行。前面试过一次worker部署，无意中成功了，但是网速慢，而且出现油管广告就卡死，要重新点视频。 我v2rayN升级后貌似可用了，但导入到华为pad里的v2box 好像还是会被广告卡死，视频只能播放10秒左右。
