### ISSUE TITLE
DeprecateWarning

### ISSUE THREAD

**Issue by RzdPai** [yonggekkk/Cloudflare_vless_trojan#168]
sing box的配置格式太旧了会提示弃用警告
![Screenshot_2024-12-01-22-35-05-42_d2ee0e1115b0a64ebff5994ebce8502f](https://github.com/user-attachments/assets/e6d96a7b-a4ac-4e88-9edf-5bdec35e8f50)
![Screenshot_2024-12-01-22-35-08-54_d2ee0e1115b0a64ebff5994ebce8502f](https://github.com/user-attachments/assets/d3a2c530-4e4a-434e-ac31-e030b83aed14)

**Comment by yonggekkk** [comment]
了解！到时会改！

**Comment by yonggekkk** [comment]
已更新

**Comment by mrsoshining** [comment]
大佬、还有这个是什么回事？
![IMG_6996](https://github.com/user-attachments/assets/24bd43c5-3a52-490f-b758-b1893ad28ba1)

**Comment by yonggekkk** [comment]
> 大佬、还有这个是什么回事？ ![IMG_6996](https://private-user-images.githubusercontent.com/32009350/395464226-24bd43c5-3a52-490f-b758-b1893ad28ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzUxODAsIm5iZiI6MTczNDA3NDg4MCwicGF0aCI6Ii8zMjAwOTM1MC8zOTU0NjQyMjYtMjRiZDQzYzUtM2E1Mi00OTBmLWI3NTgtYjE4OTNhZDI4YmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA3MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwY2E1YTlmMGU4ZjNkMTY2OTZmNTFhNjljMmU0YWMyN2MzYWU5OGJmNDNiMjIwZTQzOGYwNTllNTQ3YTA5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X99Yjt0njIRrsf3_07XoCHUKgTN8QvD4Hk5tHS8EpBg)

必须sing box 1.11版本以上的客户端内核

**Comment by mrsoshining** [comment]
> > 大佬、还有这个是什么回事？ ![IMG_6996](https://private-user-images.githubusercontent.com/32009350/395464226-24bd43c5-3a52-490f-b758-b1893ad28ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzUxODAsIm5iZiI6MTczNDA3NDg4MCwicGF0aCI6Ii8zMjAwOTM1MC8zOTU0NjQyMjYtMjRiZDQzYzUtM2E1Mi00OTBmLWI3NTgtYjE4OTNhZDI4YmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA3MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwY2E1YTlmMGU4ZjNkMTY2OTZmNTFhNjljMmU0YWMyN2MzYWU5OGJmNDNiMjIwZTQzOGYwNTllNTQ3YTA5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X99Yjt0njIRrsf3_07XoCHUKgTN8QvD4Hk5tHS8EpBg)
> 
> 必须sing box 1.11版本以上的客户端内核

大佬、最高版本还没到1.11呀
![IMG_6997](https://github.com/user-attachments/assets/03abb114-1937-472d-9176-4e327b70667e)

**Comment by yonggekkk** [comment]
> > > 大佬、还有这个是什么回事？ ![IMG_6996](https://private-user-images.githubusercontent.com/32009350/395464226-24bd43c5-3a52-490f-b758-b1893ad28ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzUxODAsIm5iZiI6MTczNDA3NDg4MCwicGF0aCI6Ii8zMjAwOTM1MC8zOTU0NjQyMjYtMjRiZDQzYzUtM2E1Mi00OTBmLWI3NTgtYjE4OTNhZDI4YmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA3MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwY2E1YTlmMGU4ZjNkMTY2OTZmNTFhNjljMmU0YWMyN2MzYWU5OGJmNDNiMjIwZTQzOGYwNTllNTQ3YTA5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X99Yjt0njIRrsf3_07XoCHUKgTN8QvD4Hk5tHS8EpBg)
> > 
> > 
> > 必须sing box 1.11版本以上的客户端内核
> 
> 大佬、最高版本还没到1.11呀 ![IMG_6997](https://private-user-images.githubusercontent.com/32009350/395607926-03abb114-1937-472d-9176-4e327b70667e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMDQ1ODYsIm5iZiI6MTczNDEwNDI4NiwicGF0aCI6Ii8zMjAwOTM1MC8zOTU2MDc5MjYtMDNhYmIxMTQtMTkzNy00NzJkLTkxNzYtNGUzMjdiNzA2NjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDE1MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2Y2ZiNWI1N2E0NDZhNGI1ZGUzNmY0ZWI3YmE4MzNhNWJmMTBlNjIyNDdiYjhiZDQ0NjljZWE4ODRjOGIzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QIj0QVznzHRThQ5fg6OH1Yb48He2vkzxixLRwSnl40w)

快正式版了！

**Comment by mrsoshining** [comment]
> > > > 大佬、还有这个是什么回事？ ![IMG_6996](https://private-user-images.githubusercontent.com/32009350/395464226-24bd43c5-3a52-490f-b758-b1893ad28ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzUxODAsIm5iZiI6MTczNDA3NDg4MCwicGF0aCI6Ii8zMjAwOTM1MC8zOTU0NjQyMjYtMjRiZDQzYzUtM2E1Mi00OTBmLWI3NTgtYjE4OTNhZDI4YmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA3MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwY2E1YTlmMGU4ZjNkMTY2OTZmNTFhNjljMmU0YWMyN2MzYWU5OGJmNDNiMjIwZTQzOGYwNTllNTQ3YTA5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X99Yjt0njIRrsf3_07XoCHUKgTN8QvD4Hk5tHS8EpBg)
> > > 
> > > 
> > > 必须sing box 1.11版本以上的客户端内核
> > 
> > 
> > 大佬、最高版本还没到1.11呀 ![IMG_6997](https://private-user-images.githubusercontent.com/32009350/395607926-03abb114-1937-472d-9176-4e327b70667e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMDQ1ODYsIm5iZiI6MTczNDEwNDI4NiwicGF0aCI6Ii8zMjAwOTM1MC8zOTU2MDc5MjYtMDNhYmIxMTQtMTkzNy00NzJkLTkxNzYtNGUzMjdiNzA2NjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDE1MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2Y2ZiNWI1N2E0NDZhNGI1ZGUzNmY0ZWI3YmE4MzNhNWJmMTBlNjIyNDdiYjhiZDQ0NjljZWE4ODRjOGIzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QIj0QVznzHRThQ5fg6OH1Yb48He2vkzxixLRwSnl40w)
> 
> 快正式版了！

谢谢大佬，pixel刚更新1.11了，ios再等等好了
