### ISSUE TITLE
请问Yong Ge, 如何做_worker.js的混淆，自己想DIY脚本。

### ISSUE THREAD

**Issue by bt-worm** [yonggekkk/Cloudflare_vless_trojan#169]
想看看能不能多改写脚本里的变量名称等等，减少特征。谢谢Yong Ge. :)

**Comment by yonggekkk** [comment]
谷歌下js混淆

**Comment by bt-worm** [comment]
找到了，谢谢Yong Ge.

另，想确认一下，每次更新_worker.js时候，您都会留一份明文的吧。这样我们可以每次都根据最新版的自己调整。

**Comment by yonggekkk** [comment]
> 找到了，谢谢Yong Ge.
> 
> 另，想确认一下，每次更新_worker.js时候，您都会留一份明文的吧。这样我们可以每次都根据最新版的自己调整。

是的
