### ISSUE TITLE
Error 1027 rate limit

### ISSUE THREAD

**Issue by Alison110** [yonggekkk/Cloudflare_vless_trojan#174]
Please check back later
Error 1027
 This website has been temporarily rate limited

You cannot access this site because the owner has reached their plan limits. Check back later once traffic has gone down.

If you are owner of this website, prevent this from happening again by upgrading your plan on the [Cloudflare Workers dashboard](https://dash.cloudflare.com/?account=workers/plans).

**Comment by yonggekkk** [comment]
请求超了？用pages
