### ISSUE TITLE
page搭建报1011错误

### ISSUE THREAD

**Issue by kaige1116** [yonggekkk/Cloudflare_vless_trojan#175]
绑定了自定义域名，搭建后提示1011错误。不知道是不是个例。

**Comment by yonggekkk** [comment]
用混淆代码了吗？

**Comment by kaige1116** [comment]
> 用混淆代码了吗？

是用混淆代码

**Comment by yonggekkk** [comment]
> > 用混淆代码了吗？
> 
> 是用混淆代码

新建一个不同名称的page地址重新部署

**Comment by kaige1116** [comment]
> > > 用混淆代码了吗？
> > 
> > 
> > 是用混淆代码
> 
> 新建一个不同名称的page地址重新部署

好的  我再试一下
