### ISSUE TITLE
如何指定pages指定运行文件

### ISSUE THREAD

**Issue by he110777** [yonggekkk/Cloudflare_vless_trojan#177]
![Screenshot_2024-12-03-15-36-28-433_com android chrome-edit](https://github.com/user-attachments/assets/061f2373-dcff-4fe5-b73f-898cf4890db4)

**Comment by yonggekkk** [comment]
写了：请使用上面的文件，用乱码文件。

**Comment by kaige1116** [comment]
勇哥我也有这个疑问。page部署在Vless_workers_pages路径下，cloudflare部署页面怎么设置才能指定Vless_workers_pages/_worker.js文件

**Comment by yonggekkk** [comment]
已更新
