### ISSUE TITLE
打开ip.sb，上面ipv4显示是台湾，下面ipv6是香港，怎么让ipv6也显示台湾 或者新加坡呢

### ISSUE THREAD

**Issue by flylj999** [yonggekkk/Cloudflare_vless_trojan#178]
香港有些服务不支持 可能是不是ipv6显示是的原因，怎么让ipv6 和ipv4显示的一致啊

**Comment by yonggekkk** [comment]
ip.sb是个神奇的网站，v4显示cf网站落地，v6显示非cf网站落地
不理解我上面的话？可以先看https://youtu.be/NaLd-orwFUE

**Comment by flylj999** [comment]
我发现看直播时候，用ipv6节点，会断，然后又自动连上，过一会又断又连，怎么回事，是不是ipv4 就没事


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月3日 18:55 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [yonggekkk/Cloudflare_vless_trojan] 打开ip.sb，上面ipv4显示是台湾，下面ipv6是香港，怎么让ipv6也显示台湾 或者新加坡呢 (Issue #178) |

ip.sb是个神奇的网站，v4显示cf网站落地，v6显示非cf网站落地
不理解我上面的话？可以先看https://youtu.be/NaLd-orwFUE
