### ISSUE TITLE
默认的v2rayng启用的是1.1.1.1DNS会有冲突导致无法使用

### ISSUE THREAD

**Issue by xxntmctx** [yonggekkk/Cloudflare_vless_trojan#179]
下面是是v2rayng的 debug日志
--------- beginning of main
12-04 10:40:39.174 I/com.v2ray.ang( 9761): This is sticky GC, maxfree is 33554432 minfree is 8388608
12-04 10:40:41.117 I/GoLog   (10549): loading core config
12-04 10:40:41.120 I/GoLog   (10549): Preparing Domain: usa.visa.com:443
12-04 10:40:41.171 I/GoLog   (10549): Prepare Result:
12-04 10:40:41.171 I/GoLog   (10549):  Domain: usa.visa.com
12-04 10:40:41.171 I/GoLog   (10549):  Port: 443
12-04 10:40:41.171 I/GoLog   (10549):  IPs: [172.64.148.174 104.18.39.82]
12-04 10:40:41.581 I/GoLog   (10549): new core
12-04 10:40:41.581 I/GoLog   (10549): [Debug] app/log: Logger started
12-04 10:40:41.590 I/GoLog   (10549): [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
12-04 10:40:41.590 I/GoLog   (10549): [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
12-04 10:40:41.590 I/GoLog   (10549): [Info] app/dns: DNS: created UDP client initialized for 223.5.5.5:53
12-04 10:40:41.599 I/GoLog   (10549): [Debug] app/router: MphDomainMatcher is enabled for 2 domain rule(s)
12-04 10:40:41.600 I/GoLog   (10549): [Debug] app/router: MphDomainMatcher is enabled for 719 domain rule(s)
12-04 10:40:41.600 I/GoLog   (10549): [Debug] app/router: MphDomainMatcher is enabled for 138 domain rule(s)
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/router: MphDomainMatcher is enabled for 10676 domain rule(s)
12-04 10:40:41.606 I/GoLog   (10549): start core
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:10808
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:10809
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/stats: create new counter outbound>>>proxy>>>traffic>>>uplink
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/stats: create new counter outbound>>>proxy>>>traffic>>>downlink
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/stats: create new counter outbound>>>direct>>>traffic>>>uplink
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/stats: create new counter outbound>>>direct>>>traffic>>>downlink
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/stats: create new counter outbound>>>block>>>traffic>>>uplink
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/stats: create new counter outbound>>>block>>>traffic>>>downlink
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/stats: create new counter outbound>>>fragment>>>traffic>>>uplink
12-04 10:40:41.606 I/GoLog   (10549): [Debug] app/stats: create new counter outbound>>>fragment>>>traffic>>>downlink
12-04 10:40:41.606 I/GoLog   (10549): [Info] transport/internet/tcp: listening TCP on 127.0.0.1:10808
12-04 10:40:41.607 I/GoLog   (10549): [Info] transport/internet/udp: listening UDP on 127.0.0.1:10808
12-04 10:40:41.607 I/GoLog   (10549): [Info] transport/internet/tcp: listening TCP on 127.0.0.1:10809
12-04 10:40:41.607 I/GoLog   (10549): [Warning] core: Xray 24.10.16 started
12-04 10:40:41.641 D/com.v2ray.ang(10549): [/data/app/~~NsXNuhwZT3aRwc3AXHbPhw==/com.v2ray.ang-bkpOZSwdMKC8ayoR8tDABw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --netif-ip6addr, da26:2626::2]
12-04 10:40:41.643 D/com.v2ray.ang(10549): Process[pid=21929, hasExited=false]
12-04 10:40:41.643 D/com.v2ray.ang(10549): /data/user/0/com.v2ray.ang/files/sock_path
12-04 10:40:41.645 D/com.v2ray.ang(10549): libtun2socks.so check
12-04 10:40:41.649 I/tun2socks(21929): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
12-04 10:40:41.657 D/com.v2ray.ang(10549): runPlugin
12-04 10:40:41.695 D/com.v2ray.ang(10549): sendFd tries: 0
12-04 10:40:41.696 I/tun2socks(21929): NOTICE(tun2socks): entering event loop
12-04 10:40:41.783 I/GoLog   (10549): [Info] [2282029206] proxy/socks: client UDP connection from udp:127.0.0.1:45471
12-04 10:40:41.783 I/GoLog   (10549): [Debug] [2282029206] proxy/socks: send packet to udp:1.1.1.1:53 with 34 bytes
12-04 10:40:41.783 I/GoLog   (10549): [Debug] [2282029206] transport/internet/udp: dispatch request to: udp:1.1.1.1:53
12-04 10:40:41.783 I/GoLog   (10549): [Info] [2282029206] transport/internet/udp: establishing new connection for udp:1.1.1.1:53
12-04 10:40:41.783 I/GoLog   (10549): [Info] [2282029206] app/dispatcher: taking detour [proxy] for [udp:1.1.1.1:53]
12-04 10:40:41.783 I/GoLog   (10549): from udp:127.0.0.1:45471 accepted udp:1.1.1.1:53 [socks -> proxy]
12-04 10:40:41.783 I/GoLog   (10549): [Info] [1645717408] proxy/socks: client UDP connection from udp:127.0.0.1:41340
12-04 10:40:41.783 I/GoLog   (10549): [Debug] [1645717408] proxy/socks: send packet to udp:1.1.1.1:53 with 34 bytes
12-04 10:40:41.783 I/GoLog   (10549): [Debug] [1645717408] transport/internet/udp: dispatch request to: udp:1.1.1.1:53
12-04 10:40:41.783 I/GoLog   (10549): [Info] [1645717408] transport/internet/udp: establishing new connection for udp:1.1.1.1:53
12-04 10:4

**Comment by xxntmctx** [comment]
我多次测试发现好像确实是DNS问题，默认的v2rayng启用的是1.1.1.1DNS会有冲突，只要在设置里面把VPN DNS改成其他的DNS例如8.8.8.8就全部正常了

**Comment by yonggekkk** [comment]
NG设置中，把两个DNS设置打钩
