### ISSUE TITLE
CF优选官方IP(无交互三地区电脑版).zip 系统提示为病毒，无法下载

### ISSUE THREAD

**Issue by MMuoux** [yonggekkk/Cloudflare_vless_trojan#181]
我在下载这个压缩包的时候，我用的edge浏览器提示为病毒，直接不让下载，我又尝试了把整个项目下载下来后再解压，然后再找到这个压缩包解压，系统直接提示病毒，不让解压然后把这个压缩包给删掉了
<img width="627" alt="屏幕截图 2024-12-04 220517" src="https://github.com/user-attachments/assets/3b9037f9-bdd1-42df-afdb-602855a90c57">

**Comment by yonggekkk** [comment]
应用没做包装处理就这样。。。浏览器安全设置下即可
