### ISSUE TITLE
新的混淆版本使用一段时间后自定义域名会被CF封禁，修改新的二级域名后才能重新使用。

### ISSUE THREAD

**Issue by wzl0904** [yonggekkk/Cloudflare_vless_trojan#182]
不知道CF是怎么识别封禁的   
补充： 是不是直接通过反代域名直接识别的  我用的tw那个域名

**Comment by yonggekkk** [comment]
不用自定义域是否正常？或者换个CF账号试试

**Comment by wzl0904** [comment]
> 不用自定义域是否正常？或者换个CF账号试试

我在的地方好像本身CF的域名（*.workers.dev）就不能访问  一直都是用自定义的

**Comment by yonggekkk** [comment]
> > 不用自定义域是否正常？或者换个CF账号试试
> 
> 我在的地方好像本身CF的域名（*.workers.dev）就不能访问 一直都是用自定义的

用80系端口关TLS，或者443系端口开分片开TLS，workers域名都可以用

**Comment by Poiig** [comment]
![image](https://github.com/user-attachments/assets/3482ba67-d86f-47b9-860e-e99eceac5bea)
我也是一样的，昨晚弄好的，用的自定义域名+vless，早上就这样了

**Comment by wzl0904** [comment]
> > > 不用自定义域是否正常？或者换个CF账号试试
> > 
> > 
> > 我在的地方好像本身CF的域名（*.workers.dev）就不能访问 一直都是用自定义的
> 
> 用80系端口关TLS，或者443系端口开分片开TLS，workers域名都可以用

不挂代理 我在浏览器里直接访问https的workers地址  无法访问  需要在CF里配置？

**Comment by feiqingbiss** [comment]
新版本部署后还是1101报错，不用自定义域都1101.

**Comment by feiqingbiss** [comment]
尝试修改自定义域再修改回来就好了。。。。。

**Comment by wzl0904** [comment]
> 尝试修改自定义域再修改回来就好了。。。。。

现在只能来回切不同二级域名 还没试过之前用过的是否能继续使用

**Comment by Poiig** [comment]
> > 尝试修改自定义域再修改回来就好了。。。。。
> 
> 现在只能来回切不同二级域名 还没试过之前用过的是否能继续使用

我看我的改了二级域名也是无效的

**Comment by wzl0904** [comment]
是不是直接通过反代域名直接识别的 我用的tw那个域名

**Comment by Poiig** [comment]
现在默认打开域名是一串网络相关信息，可以伪装成其他站点吗，怎么配置，能教下么

**Comment by feiqingbiss** [comment]
我的操作，第一步更新_worker.js内容，发现默认域名与自定义域都是1101，然后更改二级自定义域，发现正常，然后再还回原有二级自定义域，也正常。打开默认域名，还是1101，修改worker命名，正常，没有再尝试更换回原有worker名称，都是abc这种简单名称。

**Comment by vampireisoves** [comment]
部署完成就1101了

**Comment by yonggekkk** [comment]
一直1101的，注册个新CF账号吧
