### ISSUE TITLE
用vless worker部署的vpn，打开网页报错

### ISSUE THREAD

**Issue by jiojiojackson** [yonggekkk/Cloudflare_vless_trojan#183]
![error](https://github.com/user-attachments/assets/2456f12c-5297-4827-9119-d5078ea9b17f)

**Comment by yonggekkk** [comment]
域名问题？换个域名，或者不用域名

**Comment by jiojiojackson** [comment]
换个域名还是一样。worker不用自定义域名的话，国内是访问不了的。用你以前2024年6月份的代码，是没有这个问题的。但是现在用6月份的代码，会报1101错误。

**Comment by yonggekkk** [comment]
> 换个域名还是一样。worker不用自定义域名的话，国内是访问不了的。用你以前2024年6月份的代码，是没有这个问题的。但是现在用6月份的代码，会报1101错误。

没必要访问workers，直接手搓

**Comment by jiojiojackson** [comment]
怎样手搓？可以指导一下吗？

**Comment by yonggekkk** [comment]
> 怎样手搓？可以指导一下吗？

https://youtu.be/WwAeLyEz6jY
