### ISSUE TITLE
pages部署的trojan，1101报错

### ISSUE THREAD

**Issue by k787379338** [yonggekkk/Cloudflare_vless_trojan#184]
pages部署的trojan，1101报错

**Comment by yonggekkk** [comment]
本地上传部署即可

**Comment by k787379338** [comment]
本来就是本地上传的

**Comment by k787379338** [comment]
![Screenshot_20241205_130557_com UCMobile](https://github.com/user-attachments/assets/8a0d52ed-152d-4de3-823e-9f99dd719858)

**Comment by yonggekkk** [comment]
自定义域或者换个CF账号试试

**Comment by k787379338** [comment]
换了个账号就好了，这是什么情况？

**Comment by yonggekkk** [comment]
> 换了个账号就好了，这是什么情况？

这几天就这样。。呵呵

**Comment by kaige1116** [comment]
应该是屏蔽了vless 或者trojan字段 包括文件目录名称。我的vless也是1011
