### ISSUE TITLE
大佬 用你的cf ip优选工具亚洲里 我想选新加坡 韩国的ip比较快的怎么做

### ISSUE THREAD

**Issue by flylj999** [yonggekkk/Cloudflare_vless_trojan#186]
现在亚洲最快的都是香港的

**Comment by yonggekkk** [comment]
新加坡 韩国其实都在里面的，在选择过程中，因延迟太高或不能用被淘汰了，所以没显示出来

**Comment by flylj999** [comment]
好的，还有个问题。在设置变量里，最多只能有13个节点吗，我看默认6个，我如果加了变量就直接换了，没法14 15的向后面加 是吗。也就是说 订阅链接直接导入，直接订阅最多是6个了

**Comment by flylj999** [comment]
好的 明白了。不过我还是想要个 韩国 新加坡的 ipv6的节点，慢一点也行，不知道怎么操作，扫出来的全是最快的香港节点

**Comment by yonggekkk** [comment]
> 好的 明白了。不过我还是想要个 韩国 新加坡的 ipv6的节点，慢一点也行，不知道怎么操作，扫出来的全是最快的香港节点

双击运行cf.exe。输入全部节点，结果文件中你可以自己筛选
