### ISSUE TITLE
Vless_workers_pages OK，为什么trojan同样步骤操作，页面加上uuid后访问页面不正常啊

### ISSUE THREAD

**Issue by kevon2019** [yonggekkk/Cloudflare_vless_trojan#188]
Vless_workers_pages OK，为什么trojan workers同样步骤操作，页面加上uuid后访问页面不正常啊？勇哥

**Comment by kevon2019** [comment]
{
    "clientTcpRtt": 1,
    "longitude": "139.68990",
    "httpProtocol": "HTTP/2",
    "tlsCipher": "AEAD-AES128-GCM-SHA256",
    "continent": "AS",
    "asn": 38136,
    "clientAcceptEncoding": "gzip, deflate, br, zstd",
    "country": "JP",
    "verifiedBotCategory": "",
    "tlsClientAuth": {
        "certIssuerDNLegacy": "",
        "certIssuerSKI": "",
        "certSubjectDNRFC2253": "",
        "certSubjectDNLegacy": "",
        "certFingerprintSHA256": "",
        "certNotBefore": "",
        "certSKI": "",
        "certSerial": "",
        "certIssuerDN": "",
        "certVerified": "NONE",
        "certNotAfter": "",
        "certSubjectDN": "",
        "certPresented": "0",
        "certRevoked": "0",
        "certIssuerSerial": "",
        "certIssuerDNRFC2253": "",
        "certFingerprintSHA1": ""
    },
    "tlsExportedAuthenticator": {
        "clientFinished": "c1bd167888eca27d72393efadd283cb713f74795578d13f05c0056c9d632f38d",
        "clientHandshake": "f556b2c98e1e0ea7dee08b037d78839c51468fdd2887e5cf6c2a2f05590a21bc",
        "serverHandshake": "7a2be263990d0889501c931ab2ed5ecdd34ecec999b8935a35b120e79d86abdf",
        "serverFinished": "4f1f1f3fe93d09595e2033ed4e9c8477775bdd80968ce14ca84039651a607468"
    },
    "tlsVersion": "TLSv1.3",
    "city": "Tokyo",
    "timezone": "Asia/Tokyo",
    "colo": "NRT",
    "tlsClientHelloLength": "2002",
    "edgeRequestKeepAliveStatus": 1,
    "postalCode": "151-0053",
    "region": "Tokyo",
    "latitude": "35.68930",
    "requestPriority": "weight=256;exclusive=1",
    "regionCode": "13",
    "asOrganization": "Akari Networks",
    "tlsClientExtensionsSha1": "d756XXjtv1NEPZBYBPT3P5Odkes=",
    "tlsClientRandom": "XA2PwP5lAw8SUo6LnMiki28AIR3c77VIfNLLmI/MjeU="
}

**Comment by yonggekkk** [comment]
看项目说明，trojan变量名是什么？并不是uuid
