### ISSUE TITLE
关于使用优选反代ip和官方代ip工具的问题

### ISSUE THREAD

**Issue by MMuoux** [yonggekkk/Cloudflare_vless_trojan#190]
有几个疑问，**！1！使用官方ip工具的时候是要清除系统代理对吧**，**！2！然后使用反代ip工具的时候要不要清除系统代理啊**，我开着和关闭都试了好几次，选出来的反代ip能正常使用的时候很少，我好不容易选出来一个gpt和cf可以进的反代ip，但是discord又不让进了，我查chatgpt了，discord也是使用cf的cdn网络，但是就是不给进，我感觉很奇怪，进一步问gpt，给我的解答是discord可能对这个ip做出了限制，很难受，我又分别在开启和关闭代理的情况下使用反代ip工具，搞了半天没搞出来一个能用的............我没办法就换回了默认的反代ip，使用起来没有问题，discord，gpt等都可以访问了，我就想问一下，**反代ip是使用默认就行还是说自己用工具优选会更好啊**，因为看视频里说uuid一定要自己重设才行，就担心用默认的会不会不太好。
还说一句，哥，真的很感谢您，您的节点教程真的给了我很大的帮助，感谢！！！！！！！！！！

**Comment by yonggekkk** [comment]
1：本地中国网络环境下运行
2：本地中国网络环境下运行
3：discord不是CF的CDN网络吧，不然可以当优选IP了
4：IP用默认还是自己选，看你喜欢
4：uuid默认可以用，但大家都在用同一个
你的描述有点出入，建议看下那几期原理说明
