### ISSUE TITLE
新worker-vless代码报错……麻烦甬哥关注！

### ISSUE THREAD

**Issue by HaHaIsMe** [yonggekkk/Cloudflare_vless_trojan#191]
用之前代码布置Worker一切正常，今天突然挂掉……提示1101和522：（……
看到甬哥更新了代码，于是更新并重新部署，但Worker跑不起来，提示代码错……检查了下都是关于import("@cloudflare/workers-types") ，我是代码小白，还有请甬哥关注指引哟！大谢……

**Comment by yonggekkk** [comment]
重新注册个cf账号

**Comment by HaHaIsMe** [comment]
> 重新注册个cf账号

收到……谢谢您这么快的回复！
如果每次都重新注册CF账号，成本有点高呢……目前这个账号上的Trojan代码还没问题，这阵儿CF好像在嘬妖瞎折腾，我是不是应该再等等……等到风平浪静后再重建，您给我个意见？

**Comment by yonggekkk** [comment]
新建个项目，新代码

**Comment by HaHaIsMe** [comment]
> 新建个项目，新代码
收到，马上尝试……

**Comment by HaHaIsMe** [comment]
> 新建个项目，新代码

OK……跑起来了！多谢……
我再跟您的视频学习，孩子读书要用外网，墙内不易……幸亏有你的指引！
