### ISSUE TITLE
订阅节点优选IP 变量名称是什么

### ISSUE THREAD

**Issue by xmaec555** [yonggekkk/Cloudflare_vless_trojan#192]
如题

**Comment by yonggekkk** [comment]
https://github.com/yonggekkk/Cloudflare_vless_trojan?tab=readme-ov-file#%E4%B8%80cf-vless%E8%8A%82%E7%82%B9%E5%8F%AF%E8%AE%BE%E7%BD%AE%E7%9A%84%E5%8F%98%E9%87%8F%E5%86%85%E5%AE%B9

**Comment by xmaec555** [comment]
谢谢，BPB面板 会1101  能出期视频吗

**Comment by yonggekkk** [comment]
> 谢谢，BPB面板 会1101 能出期视频吗

这个要问bpb作者修复了！
