### ISSUE TITLE
看不到代码了

### ISSUE THREAD

**Issue by leecoo7** [yonggekkk/Cloudflare_vless_trojan#195]
https://github.com/yonggekkk/Cloudflare_vless_trojan/blob/2a701be1bf856a0a73f75f835077de7db0fc67a5/Vless_workers_pages/_worker.js#L1

**Comment by yonggekkk** [comment]
> https://github.com/yonggekkk/Cloudflare_vless_trojan/blob/2a701be1bf856a0a73f75f835077de7db0fc67a5/Vless_workers_pages/_worker.js#L1

用的就是这个，过两天正式出期教程吧
