### ISSUE TITLE
勇哥，用你昨天更新的代码部署pages会出现1101

### ISSUE THREAD

**Issue by chineseoptv** [yonggekkk/Cloudflare_vless_trojan#196]
勇哥，用你昨天更新的代码试了一下
部署pages会出现1101
部署workers则正常

**Comment by kaige1116** [comment]
我也是，部署4次了，每次差不多一天又会1101

**Comment by MMuoux** [comment]
我也是，1101了

**Comment by yonggekkk** [comment]
Pges出现1101的，不要用自定义域或者新注册个CF账号试试

**Comment by MMuoux** [comment]
我刚才测试了一下，我在昨天失效的work和page里面直接重新更换代码，重新部署，结果都不行。我又试了重新建立新的work和page，再去更换代码和重新部署，结果又行了。我上一条勇哥发的说 {Pges出现1101的，不要用自定义域或者新注册个CF账号试试}，我也去试了，我新建立的work绑了自定义域，新建立的page我试了不绑和绑自定义域，结果都行，都可以正常使用

**Comment by MMuoux** [comment]
我测试出的结论是work和page被522或1101之后，项目就被封了，这个被封的work和page就不能再继续使用了，就算更换新的代码或重新部署也不行，只能新建work和page，

**Comment by yonggekkk** [comment]
> 我测试出的结论是work和page被522或1101之后，项目就被封了，这个被封的work和page就不能再继续使用了，就算更换新的代码或重新部署也不行，只能新建work和page，

原项目1101当然就废了，必须新建

**Comment by chineseoptv** [comment]
> 我刚才测试了一下，我在昨天失效的work和page里面直接重新更换代码，重新部署，结果都不行。我又试了重新建立新的work和page，再去更换代码和重新部署，结果又行了。我上一条勇哥发的说 {Pges出现1101的，不要用自定义域或者新注册个CF账号试试}，我也去试了，我新建立的work绑了自定义域，新建立的page我试了不绑和绑自定义域，结果都行，都可以正常使用

我新注册了一个新账号测试了一下，结果更差，work和page都出现1101，就很迷！

**Comment by yonggekkk** [comment]
> > Pges出现1101的，不要用自定义域或者新注册个CF账号试试
> 
> ![屏幕截图 2024-12-07 171747](https://private-user-images.githubusercontent.com/189615572/393499122-ccdc3ddf-6a62-4ccf-873b-ec9afb5ea5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NjUwNzYsIm5iZiI6MTczMzU2NDc3NiwicGF0aCI6Ii8xODk2MTU1NzIvMzkzNDk5MTIyLWNjZGMzZGRmLTZhNjItNGNjZi04NzNiLWVjOWFmYjVlYTVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwOTQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTFhYzAzNjg0NWIxN2I5MzQyN2YxZThmODViYzljNWRjMjFiZjZjY2YwOThkN2IwNTkzNTg0NTRmMjhhOWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MFdxZ7qIG7Y7VDYTACS4oSel66NI0G-s5_8pAITt96M) ![屏幕截图 2024-12-07 171820](https://private-user-images.githubusercontent.com/189615572/393499125-e3b1a8f3-b98a-4094-bd8d-a08374a797d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NjUwNzYsIm5iZiI6MTczMzU2NDc3NiwicGF0aCI6Ii8xODk2MTU1NzIvMzkzNDk5MTI1LWUzYjFhOGYzLWI5OGEtNDA5NC1iZDhkLWEwODM3NGE3OTdkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwOTQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGU1ZmMzYWYwODM4ZThlMzExMDQ2ODZjMGRiOTU0YjVmMTZjOWIwZmRmNWM2ZjM4YTE2ODQ0ODZlMzgyYjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ujIdfvgDRUBfUtBfgLmev6JWPN7Dv9t2Oj20BHWq5tk)
> 
> 我新注册了一个新账号测试了一下，结果更差，用CF的域名以及自定义域名访问work和page都出现1101，然而在work代码编辑的预览窗口就可以看到是正常的，上面两张图都是同一个域名，真的很迷！

一切以网页为准

**Comment by chineseoptv** [comment]
> > > Pges出现1101的，不要用自定义域或者新注册个CF账号试试
> > 
> > 
> > ![屏幕截图 2024-12-07 171747](https://private-user-images.githubusercontent.com/189615572/393499122-ccdc3ddf-6a62-4ccf-873b-ec9afb5ea5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NjUwNzYsIm5iZiI6MTczMzU2NDc3NiwicGF0aCI6Ii8xODk2MTU1NzIvMzkzNDk5MTIyLWNjZGMzZGRmLTZhNjItNGNjZi04NzNiLWVjOWFmYjVlYTVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwOTQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTFhYzAzNjg0NWIxN2I5MzQyN2YxZThmODViYzljNWRjMjFiZjZjY2YwOThkN2IwNTkzNTg0NTRmMjhhOWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MFdxZ7qIG7Y7VDYTACS4oSel66NI0G-s5_8pAITt96M) ![屏幕截图 2024-12-07 171820](https://private-user-images.githubusercontent.com/189615572/393499125-e3b1a8f3-b98a-4094-bd8d-a08374a797d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NjUwNzYsIm5iZiI6MTczMzU2NDc3NiwicGF0aCI6Ii8xODk2MTU1NzIvMzkzNDk5MTI1LWUzYjFhOGYzLWI5OGEtNDA5NC1iZDhkLWEwODM3NGE3OTdkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwOTQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGU1ZmMzYWYwODM4ZThlMzExMDQ2ODZjMGRiOTU0YjVmMTZjOWIwZmRmNWM2ZjM4YTE2ODQ0ODZlMzgyYjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ujIdfvgDRUBfUtBfgLmev6JWPN7Dv9t2Oj20BHWq5tk)
> > 我新注册了一个新账号测试了一下，结果更差，用CF的域名以及自定义域名访问work和page都出现1101，然而在work代码编辑的预览窗口就可以看到是正常的，上面两张图都是同一个域名，真的很迷！
> 
> 一切以网页为准

最后我的测试得出一个结论，在同一个部署后发生1101的项目里，我其他项目都没有改动，多次禁用CF分配的域名以及再启用后1101的错误消失，自定义域名也是一样，再删除自定义域名再添加后，1101消失，恢复正常！各位可以尝试一下，我这边这么操作是有效的。

**Comment by yonggekkk** [comment]
> > > > Pges出现1101的，不要用自定义域或者新注册个CF账号试试
> > > 
> > > 
> > > ![屏幕截图 2024-12-07 171747](https://private-user-images.githubusercontent.com/189615572/393499122-ccdc3ddf-6a62-4ccf-873b-ec9afb5ea5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NjUwNzYsIm5iZiI6MTczMzU2NDc3NiwicGF0aCI6Ii8xODk2MTU1NzIvMzkzNDk5MTIyLWNjZGMzZGRmLTZhNjItNGNjZi04NzNiLWVjOWFmYjVlYTVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwOTQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTFhYzAzNjg0NWIxN2I5MzQyN2YxZThmODViYzljNWRjMjFiZjZjY2YwOThkN2IwNTkzNTg0NTRmMjhhOWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MFdxZ7qIG7Y7VDYTACS4oSel66NI0G-s5_8pAITt96M) ![屏幕截图 2024-12-07 171820](https://private-user-images.githubusercontent.com/189615572/393499125-e3b1a8f3-b98a-4094-bd8d-a08374a797d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NjUwNzYsIm5iZiI6MTczMzU2NDc3NiwicGF0aCI6Ii8xODk2MTU1NzIvMzkzNDk5MTI1LWUzYjFhOGYzLWI5OGEtNDA5NC1iZDhkLWEwODM3NGE3OTdkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QwOTQ2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGU1ZmMzYWYwODM4ZThlMzExMDQ2ODZjMGRiOTU0YjVmMTZjOWIwZmRmNWM2ZjM4YTE2ODQ0ODZlMzgyYjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ujIdfvgDRUBfUtBfgLmev6JWPN7Dv9t2Oj20BHWq5tk)
> > > 我新注册了一个新账号测试了一下，结果更差，用CF的域名以及自定义域名访问work和page都出现1101，然而在work代码编辑的预览窗口就可以看到是正常的，上面两张图都是同一个域名，真的很迷！
> > 
> > 
> > 一切以网页为准
> 
> 最后我的测试得出一个结论，在同一个部署后发生1101的项目里，我其他项目都没有改动，多次禁用CF分配的域名以及再启用后1101的错误消失，自定义域名也是一样，再删除自定义域名再添加后，1101消失，恢复正常！各位可以尝试一下，我这边这么操作是有效的。

这都行？被你发现了。。给力。。
