### ISSUE TITLE
用的workers，出现522错误

### ISSUE THREAD

**Issue by lovelydebra** [yonggekkk/Cloudflare_vless_trojan#198]
1. 用的workers，出现522错误
2. 用了自定义域名，可以ping通，但是获取不了订阅地址。
3. 需要重建workers，但是一天后又不能使用了。

 是CF在识别并封禁这种行为吗？

**Comment by yonggekkk** [comment]
https://github.com/yonggekkk/Cloudflare_vless_trojan/issues/196#issuecomment-2525053582

**Comment by lovelydebra** [comment]
重新使能分配的域名，重新添加自定义域名都不管用，始终是522错误，同样的代码重新新建worker就可以了
