### ISSUE TITLE
大佬，默认的proxyip好像坏了

### ISSUE THREAD

**Issue by flylj999** [yonggekkk/Cloudflare_vless_trojan#199]
ip.sb gpt什么的都打不开了哦

**Comment by yonggekkk** [comment]
试了下可以用呀

**Comment by flylj999** [comment]
我昨天试了不行啊，自己换了个。还有订阅链接可以导入pc 上的clashverge，但是点击显示400错误 是用不了

**Comment by xjdmelody666** [comment]
试了下是都打不开了

**Comment by zhihuihu** [comment]
是的，默认的打不开了，换了一个就可以了

**Comment by yonggekkk** [comment]
我这里怎么都正常。。。

**Comment by MMuoux** [comment]
我也是这样，以前部署的时候默认的访问不了cf类的网站，自己换了代理ip才行，然后过段时间我的代理ip也不行了，无奈之下再换回默认代理ip，结果又行了，不知道啥情况

**Comment by yonggekkk** [comment]
本周我分享几个我自建的给大家用
