### ISSUE TITLE
Seems STREAM-UP/ONE of XHTTP maybe supported

### ISSUE THREAD

**Issue by Ahmad-2213** [yonggekkk/Cloudflare_vless_trojan#201]
Hello there!
isn't there a way to deploy xhttp on workers?
seems to be faster and keep the efficiency compared to websocket.
https://github.com/XTLS/Xray-core/discussions/4113

![Screenshot_2024-12-09-08-35-04-120_org telegram messenger-edit](https://github.com/user-attachments/assets/b180e94a-517b-40bc-a2bc-fd4995c8bc24)

**Comment by yonggekkk** [comment]
这个要问上游开发者了

**Comment by Ahmad-2213** [comment]
> This is for the upstream developers.

do you know anyone who could implement this on cf?
