### ISSUE TITLE
看见的代码都是X数字！

### ISSUE THREAD

**Issue by ericzwei** [yonggekkk/Cloudflare_vless_trojan#204]
![屏幕截图 2024-12-09 223412](https://github.com/user-attachments/assets/465a56a3-7829-496d-98b1-5af816dd5526)
https://github.com/yonggekkk/Cloudflare_vless_trojan/blob/3d592db951011ce230132a55609de08564890ab2/Vless_workers_pages/_worker.js#L1

**Comment by yonggekkk** [comment]
正常
教程看https://youtu.be/cVLxDKHTv6w
本周更新正式教程
