### ISSUE TITLE
发现ios上可以语音聊天的chatgpt无法使用，换成机场节点可以

### ISSUE THREAD

**Issue by flylj999** [yonggekkk/Cloudflare_vless_trojan#205]
网页端都可以 ，不知道怎么回事。好像显示ISP什么，如果点语音直接连接失败

**Comment by yonggekkk** [comment]
不支持UDP吧

**Comment by flylj999** [comment]
哦哦 那我们部署的节点都是udp的吗在 2024年12月11日，09:26，甬哥侃侃侃ygkkk ***@***.***> 写道：﻿
原因应该是不支持UDP吧，正常
