### ISSUE TITLE
请问 使用自定义域有什么用啊

### ISSUE THREAD

**Issue by flylj999** [yonggekkk/Cloudflare_vless_trojan#206]
自定域好记，但是后面还有一堆uuid，还是无法进入订阅链接界面，也就得不到订阅链接。
那用自定义域是为了什么呢

**Comment by yonggekkk** [comment]
自定义域并不是必须的，随意。。
进入链接界面可以看下这期教程：https://youtu.be/cVLxDKHTv6w
