### ISSUE TITLE
CF优选官方IP(无交互三地区电脑版)在win7X64旗舰版中无法使用

### ISSUE THREAD

**Issue by zyrubber** [yonggekkk/Cloudflare_vless_trojan#208]
![未标题-1](https://github.com/user-attachments/assets/d04db4b9-31ef-4d60-8266-4161405e6457)

*以管理员身份运行* 也不行

**Comment by yonggekkk** [comment]
是的。。你可以直接运行cf.exe文件，输出所有结果文件
