### ISSUE TITLE
大佬 在安卓客户端看pikpak时 为什么拖动几下就提示网络请求超时2004错误

### ISSUE THREAD

**Issue by flylj999** [yonggekkk/Cloudflare_vless_trojan#209]
然后就停了，要是用机场节点就没事。怎么解决啊

**Comment by yonggekkk** [comment]
试试别的客户端会有同样的问题吗？电脑上也试试

**Comment by flylj999** [comment]
没别的了吧 安卓上就这个官方的。电脑上没事 在 2024年12月12日，07:54，甬哥侃侃侃ygkkk ***@***.***> 写道：﻿
试试别的客户端会有同样的问题吗？电脑上也试试

**Comment by yonggekkk** [comment]
如果是CF节点跳IP引起的，那也正常

**Comment by flylj999** [comment]
可以怎么设置不让跳ip吗在 2024年12月12日，08:01，甬哥侃侃侃ygkkk ***@***.***> 写道：﻿
如果是CF节点跳IP引起的，那也正常

**Comment by yonggekkk** [comment]
成本有点高，要用另外的服务器来纠正
