### ISSUE TITLE
(*꒦ິ⌓꒦ີ)我电脑上和手机上使用同一个节点真连接延迟差异很大

### ISSUE THREAD

**Issue by MMuoux** [yonggekkk/Cloudflare_vless_trojan#210]
我电脑上使用的是v2rayn，
手机上使用的是v2rayng，
家里宽带是电信的，
我在使用优选官方ip工具的时候他现实我的网络支持v6和v4，但是我并没有使用v6，用的v4，v2rayn和v2rayng上的 ipv6 优先也并没有打开，
使用的是勇哥的work，page项目，work和page建立的节点都遇到了标题所说的问题，
我也使用了优选官方ip工具优选了ip，选出来的延迟最低的ip是美国的，换上这个官方ip之后所有节点的延迟都在160ms左右（电脑上）
但是等我把节点分享到手机上的v2rayng之后，延迟却是1000ms，最低最低都是900ms，很难绷 看油管视频都有时候一卡一卡的，
我在tg群里也问了，有人说是我家路由器的问题，但也无法确定，
我还询问了别人的延迟大概多少，他们好几个人都说自己的电脑和手机延迟差异不大，甚至手机更快，只有60ms左右的延迟，这让我感到很惊讶，（他们也是用的workpage项目），告诉我延迟的这几个人中有人用的clash，有人用的v2rayn和v2rayng，
我就在想，为啥我的延迟会比他们高这么多，手机电脑延迟差异还这么大，这我真没搞懂，
我人在湖北的左下角，Steam下载服务器自动选择的是重庆的服务器
我不清楚是不是我地区的问题，延迟就是这么高，
但是，我这个延迟，和群里那几个60ms延迟，甚至手机更快的人，差别也太大了吧
(。•́︿•̀。)

**Comment by yonggekkk** [comment]
自测。换客户端、重启手机、用别的手机、用手机网络。。。这四个情况测试下
