### ISSUE TITLE
Web Browsing Don't Work at all

### ISSUE THREAD

**Issue by foodiemee4** [yonggekkk/Cloudflare_vless_trojan#212]
Sorry for opening issue because I don't know how to fix this .
I am using worker Deployment . It's Okay in FB , Messenger , Telegram , etc.
But Web Browsing Don't Work at all for all websites.
I don't know where I went wrong.
Anyone else experiencing same like me ?
If you have solution , please let me know.
Thanks

**Comment by yonggekkk** [comment]
检测下你的客户端
