### ISSUE TITLE
恳请在serv00增加tuic5节点。

### ISSUE THREAD

**Issue by ssfeng72** [yonggekkk/Cloudflare_vless_trojan#223]
serv00建tuic5节点速度最快，比hy2还要快。其他脚本都是默认在被墙的ip上建节点，建完节点hy2和tuic5都不能用。而甬哥的脚本可选择serv00三个ip中不被墙的ip建节点，恳请甬哥修改老王sing-box安装脚本，支持一键三协议：tuic5、vmess-ws(argo)、hysteria2。万分感谢！

**Comment by yonggekkk** [comment]
两个UDP只能选择其一。选择hy2，不选择tuic是因为hy2，客户端都支持。

**Comment by ssfeng72** [comment]
reality在serv00太慢。我可以不要reality，一个tcp端口选择wm argo，两个udp，一个选hy2，另一个选tuic5.一键脚本去除reality，只保留wm、hy2和tuic5.

**Comment by yonggekkk** [comment]
本项目reality是基础。

**Comment by YominRa** [comment]
想请教一下勇哥，Cloudflare的workers里面能用hysteria2或者tuic5之类的协议提高链接速度吗？感觉VLESS到晚高峰卡的很厉害

**Comment by yonggekkk** [comment]
> 想请教一下勇哥，Cloudflare的workers里面能用hysteria2或者tuic5之类的协议提高链接速度吗？感觉VLESS到晚高峰卡的很厉害

不支持
