### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by fsf678** [yonggekkk/Cloudflare_vless_trojan#225]
![image](https://github.com/user-attachments/assets/6959972d-bdb0-4e45-bad8-bdae3f483709)
脚本运行一段时间（两三天？）后进入就会这样
而绑定一个新的域名后就能重新使用了
请问这是脚本的问题吗
![image](https://github.com/user-attachments/assets/30d41988-cebf-478f-a632-5e0e14fb2556)

**Comment by yonggekkk** [comment]
建议不用自定义域名

**Comment by fsf678** [comment]
![image](https://github.com/user-attachments/assets/513604e1-643f-4797-b237-ea32a0e74568)
默认的.workers.dev打不开，请问有推荐的解决方案吗

**Comment by yonggekkk** [comment]
看项目中视频教程说明
