### ISSUE TITLE
Google apps and sites not working with new pages

### ISSUE THREAD

**Issue by 3lei** [yonggekkk/Cloudflare_vless_trojan#226]
Hello, I made 3 more pages with your awsome code but non of google play store and youtube could not open.
Should i do something else to make it work?

**Comment by yonggekkk** [comment]
Try another client

**Comment by 3lei** [comment]
i tried worker too it can open google play but no download. I did step by step from :
https://www.youtube.com/watch?v=QSFaP5EVI04
your video.

**Comment by 3lei** [comment]
worker log on google play store:

[1.1.1.1:443--0.2003201927130016 tcp ] readableWebSocketStream is close
Dec 20, 22:59:04.860
[1.1.1.1:443--0.2003201927130016 tcp ] remoteConnection!.readable is close with hasIncomingData is true
Dec 20, 22:59:04.568
[1.1.1.1:443--0.2003201927130016 tcp ] connected to proxy.anghazi.filegear-sg.me:443
Dec 20, 22:59:04.568
[1.1.1.1:443--0.2003201927130016 tcp ] retry
Dec 20, 22:59:04.568
[1.1.1.1:443--0.2003201927130016 tcp ] remoteConnection!.readable is close with hasIncomingData is false
Dec 20, 22:59:04.458
[1.1.1.1:443--0.2003201927130016 tcp ] connected to www.1.1.1.1.sslip.io:443
Dec 20, 22:59:04.458
checkUuidInApi: false, userID:    **** **** ******
Dec 20, 22:59:04.458
Error: ReferenceError: getApiResponse is not defined
Dec 20, 22:59:04.458
Error: ReferenceError: getApiResponse is not defined
Dec 20, 22:59:04.335
ProxyPort: 443
Dec 20, 22:59:04.335
ProxyIP: proxy.anghazi.filegear-sg.me
Dec 20, 22:59:04.335
GET https://shid1234.sziae68.workers.dev/pyip=**************
Dec 20, 22:58:58.873
[1.1.1.1:53--0.4516976487743125 udp ] webSocketServer has error
Dec 20, 22:58:58.873
[1.1.1.1:53--0.4516976487743125 udp ] readableWebSocketStream is close
Dec 20, 22:58:58.374
[1.1.1.1:53--0.8990976746520887 udp ] readableWebSocketStream is close
Dec 20, 22:58:58.214
Network connection lost.

**Comment by 3lei** [comment]
I also tried bpb worker and pages that with obfuscated version but taht will error 1101 error.
on other account that not taken error 1101 with bpb all works fine ( youtube , google , google play and other) .
I dont know that I made mistake with your code or something else happened all apps works fine but google apps not working correctly. I tried to change the config on v2raN after many tries I found something, If I change the ALPN to h3 and not setting the fingerprint function I could open google apps sometime just to preview but no playing videos and no downloading apps from google play store.

**Comment by 3lei** [comment]
just now I see that bpb did such bad move when all of us just like me use your work for good and families. sorry to bother you with asking. 
I didn't know that my people has no shame to be thankful to who did a good thing them.
maybe someday they remember that thankfulness is a big thing for life and friends and families.

now I will close my issue to not wasting your time with that great work that made us not limited internet in our country.
