### ISSUE TITLE
当前进程丢失，请卸载后重装脚本

### ISSUE THREAD

**Issue by lwtdzh** [yonggekkk/Cloudflare_vless_trojan#231]
![image](https://github.com/user-attachments/assets/a182ccf4-a83f-4aa8-8678-04e549efb24f)
想请问一下，serv00三合一脚本，我只想使用其中一种协议，只开了一个端口，另外两个端口随意填写的，这样会导致进程丢失么？我重装几次后都是这样，感觉和端口有一定关系，因为这个服务器只能开三个端口，我不想全部用在这里，。

**Comment by yonggekkk** [comment]
目前是这样，必须三端口

**Comment by lwtdzh** [comment]
> 目前是这样，必须三端口

好的，谢谢勇哥
