### ISSUE TITLE
自己申请的域名+TLS版本可能会用不了

### ISSUE THREAD

**Issue by mengsi16** [yonggekkk/Cloudflare_vless_trojan#234]
我之前申请了几个域名，其它域名的tls版本都还能使用但不常用，而一直在用的那个域名的tls版本突然用不了了。更新了新的workers代码也不行。但是无tls版本还是可以用。请教一下甬哥，怎么解决这个问题？
![image](https://github.com/user-attachments/assets/d45e7cac-7b66-43a6-90b4-9e97d6f17a61)
![image](https://github.com/user-attachments/assets/26168e03-1c9f-4584-aefc-f84f698bf0a6)
是域名被CF标记了还是被墙标记了？

**Comment by yonggekkk** [comment]
不好说！可能cf设置，客户端开分片试试

**Comment by mengsi16** [comment]
确实应该是被墙掉了我的域名。升级xray降级xray都试过，开分片也试过，都不行。后面我尝试断开梯子访问我自己的域名发现偶尔就访问不了了。应该是被墙标记了，没办法捏。（捂脸）

**Comment by mengsi16** [comment]
也不对，断开梯子只是偶尔不能访问，大部分时候还是可以访问的：
![image](https://github.com/user-attachments/assets/9191c198-d903-40b9-80d4-0a1bc9ab4916)
但是复制粘贴回去就是访问不了。呜呜呜，看甬哥能不能解决了。
我还试过开一个新的worker，但是新的worker用旧域名也不行。

> 确实应该是被墙掉了我的域名。升级xray降级xray都试过，开分片也试过，都不行。后面我尝试断开梯子访问我自己的域名发现偶尔就访问不了了。应该是被墙标记了，没办法捏。（捂脸）

**Comment by mengsi16** [comment]
我发现是我一开v2rayn后一段时间内我的域名就不能再访问。一段时间不用这个域名，又可以访问workers，但是一开v2rayn就不行。

**Comment by yonggekkk** [comment]
更新客户端

**Comment by mengsi16** [comment]
> 更新客户端

尝试过了。域名应该就是被墙了。我怎么测试怎么访问，cf那边workers，域名，都没有请求，DNS记录。我感觉墙的方式很特别。针对的就是这种底层协议用websocket的，难受捏

**Comment by mengsi16** [comment]
地址改成默认的workers域名挂上梯子都能有真延迟出来。但是自己的域名就是不行。到浏览器直接访问又可以访问到界面，但是回到v2rayn上就是-1，手机端也连不上。

**Comment by jerry001-free** [comment]
API Request Failed: GET /api/v4/accounts/c3b5310b7f0430e5608725fc99d47396/builds/builds/latest?external_script_ids=2fa2d652b1254bdbba0a40194be9ad96%2C5db27fe20dbe4cf88acbe54f68883e62%2C7057a9e1454341a1a9f5a7fbd4077b70%2C0158e231fa6d44529dcb4045bedb0c32 (undefined)

cfWOKER 端报错 VPN无法正常使用 无法显示订阅界面 可能是什么问题呢？
