### ISSUE TITLE
新的v24.12.22功能问题

### ISSUE THREAD

**Issue by a1171712023** [yonggekkk/Cloudflare_vless_trojan#235]
新的v24.12.22功能不太对吧，那个直接导入的按钮没有啊
![捕获1](https://github.com/user-attachments/assets/7ec61bf0-280b-46d2-931a-cd7e15b94936)
![捕获2](https://github.com/user-attachments/assets/da132196-ca69-476a-b8ce-4222e7c00b2a)

**Comment by a1171712023** [comment]
上面的图片是自己混淆的v24.12.22，下面的是混淆版v24.12.13

**Comment by yonggekkk** [comment]
好了
