### ISSUE TITLE
warnings on V2rayN

### ISSUE THREAD

**Issue by amijafi** [yonggekkk/Cloudflare_vless_trojan#236]
hi ,v2rayN warns about 2 issues when i run the configs . the log is provided down here :

2024/12/24 09:41:00 [Warning] common/errors: This feature WebSocket transport (with ALPN http/1.1, etc.) is deprecated and being migrated to XHTTP H2 & H3. Please update your config(s) according to release note and documentation before removal.

2024/12/24 09:41:00 [Warning] common/errors: This feature "host" in "headers" is deprecated and being migrated to independent "host". Please update your config(s) according to release note and documentation before removal.

xray core version : 24.12.18 latest
v2rayN version : 7.4.2 Latest

**Comment by hersenravel** [comment]
xray新版本不支持ws协议了，得换xhttp。

**Comment by yonggekkk** [comment]
As long as it can be used now
