### ISSUE TITLE
是否还支持ChatGpt

### ISSUE THREAD

**Issue by GrowingHacker** [yonggekkk/Cloudflare_vless_trojan#240]
CF上部署的节点现在好像被chatgpt拒绝访问了

**Comment by yonggekkk** [comment]
默认proxyip不行了吗？

**Comment by GrowingHacker** [comment]
嘿嘿搞错了，那个是另外一个开源脚本，你这个没问题，节点太多了搞混了

**Comment by Tead65** [comment]
If anyone is still encountering error 1101, this error has been fixed in 
https://github.com/bia-pain-bache/BPB-Worker-Panel/issues/669
