### ISSUE TITLE
希望Serv00专用脚本增加更新选项

### ISSUE THREAD

**Issue by ajmz** [yonggekkk/Cloudflare_vless_trojan#241]
希望Serv00专用脚本增加更新选项，不用卸载后重新安装。

**Comment by yonggekkk** [comment]
一次性脚本，现在，基本稳定了

**Comment by ajmz** [comment]
> 一次性脚本，现在，基本稳定了

昨天卸载后新装的脚本，生成的5个代理方式今天全不通了。
而且登录后运行脚本，curl: (6) Could not resolve host: raw.githubusercontent.
s15的账号。

**Comment by yonggekkk** [comment]
S15目前瘫痪中……等恢复吧

**Comment by ajmz** [comment]
> S15目前瘫痪中……等恢复吧

谢谢，刚刚测试，已经恢复了。

**Comment by ajmz** [comment]
> > S15目前瘫痪中……等恢复吧
> 
> 谢谢，刚刚测试，已经恢复了。

Serv00看来经常加强限制手段，脚本也相应升级，所以还是希望增加更新选项，谢谢。
