### ISSUE TITLE
Pages部署Trojan一直是404

### ISSUE THREAD

**Issue by dahaitaotaotao** [yonggekkk/Cloudflare_vless_trojan#242]
部署几次，pages的trojan都是404错误
![Uploading 微信截图_20241227131058.png…]()

**Comment by yonggekkk** [comment]
开代理与关代理都访问下试试

**Comment by dahaitaotaotao** [comment]
试过的，都是404，但用worker部署就可以访问，自定域会报1102错误

**Comment by yonggekkk** [comment]
试了，用上传方式，不用自定义域，可以用的，等2分钟即可
老是这样注册个新的CF账号试试
