### ISSUE TITLE
甬哥求教关于订阅的问题

### ISSUE THREAD

**Issue by ggyy911520** [yonggekkk/Cloudflare_vless_trojan#245]
我是Macos系统，部署好后，官方版的 sing-box 客户端订阅这个链接订阅不了节点，显示错误decode config: route.rules[0].action: json: unknown field "action" ，包括您的VPS的sing-box脚本，也是订阅不了，win的V2rayN没问题。主要是Mac系统订阅不了

**Comment by yonggekkk** [comment]
客户端内核升级到1.11
