### ISSUE TITLE
想问一下甬哥用的是什么代码混淆工具

### ISSUE THREAD

**Issue by xzlosats111** [yonggekkk/Cloudflare_vless_trojan#247]
虽然说不太可能，但是所以人代码一样防止被cf一锅端想着自己混淆一份备用，不过我混淆出来的会报错不能用
所以想问一下甬哥用的啥工具

**Comment by yonggekkk** [comment]
https://github.com/emn178/js-sha256

**Comment by xzlosats111** [comment]
今天去研究了一下，发现不会用，这怎么用于代码混淆啊，只看懂生成哈希值的功能

**Comment by ajmz** [comment]
> 今天去研究了一下，发现不会用，这怎么用于代码混淆啊，只看懂生成哈希值的功能

我也不会用，请问搞定没？
