### ISSUE TITLE
serv00小白一键脚本在s15.serv00.com上安装报错

### ISSUE THREAD

**Issue by bsinwhg** [yonggekkk/Cloudflare_vless_trojan#250]
serv00小白一键脚本在s15.serv00.com上安装报错：/tmp//sh-np.WRqe5R: linia 1: 404:: nie znaleziono polecenia

**Comment by yonggekkk** [comment]
curl -sSL https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/serv00.sh -o serv00.sh && bash serv00.sh
