### ISSUE TITLE
脚本1：CF-优选官方IP  无法使用

### ISSUE THREAD

**Issue by ArkWhit** [yonggekkk/Cloudflare_vless_trojan#251]
Termux中输入：
`curl -sSL https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/cf/cf.sh -o cf.sh && chmod +x cf.sh && bash cf.sh`
执行后提示：
`curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 3 ms: Could not connect to server`

**Comment by yonggekkk** [comment]
网络不支持github吧。挂代理跑一次，后续用bash cf.sh
