### ISSUE TITLE
trojan用pages部署 不行了吗

### ISSUE THREAD

**Issue by flylj999** [yonggekkk/Cloudflare_vless_trojan#253]
下载后是个差不多1M的文件 没错吧，然后打不开 部署后的页面啊 HTTP ERROR 404

**Comment by yonggekkk** [comment]
打开网页时，开关代理都试试

**Comment by flylj999** [comment]
开关代理都试过了，好像都不行，我就用worker部署了。另外想问下，Trojan和vless 有什么区别啊，是不是没有vless 安全？


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月31日 05:55 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [yonggekkk/Cloudflare_vless_trojan] trojan用pages部署 不行了吗 (Issue #253) |

打开网页时，开关代理都试试

**Comment by yonggekkk** [comment]
> 开关代理都试过了，好像都不行，我就用worker部署了。另外想问下，Trojan和vless 有什么区别啊，是不是没有vless 安全？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年12月31日 05:55 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***>, ***@***.***> | | 主题 | Re: [yonggekkk/Cloudflare_vless_trojan] trojan用pages部署 不行了吗 (Issue #253) | 打开网页时，开关代理都试试 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

一样的
