### ISSUE TITLE
部署完400 Bad Request错误

### ISSUE THREAD

**Issue by ghostWindows-files** [yonggekkk/Cloudflare_vless_trojan#81]
![QQ截图20240503221511](https://github.com/yonggekkk/Cloudflare-workers-pages-vless/assets/156029516/5af863c7-55da-4c10-b551-22ec50324968)
甬哥按照正常代码部署完直接报400错误,重新部署了即便还是一样,请问怎么解决

**Comment by BIBIYES** [comment]
我也一样

**Comment by yonggekkk** [comment]
看项目说明！这是正常的

**Comment by devpluse** [comment]
借楼，这个订阅后延迟怎么一直都是-1
