### ISSUE TITLE
优选反代ip中开启tls后显示无有效ip

### ISSUE THREAD

**Issue by iweec** [yonggekkk/Cloudflare_vless_trojan#85]
未开启代理，不开启tls并使用8880端口正常
![屏幕截图 2024-05-19 174956](https://github.com/yonggekkk/Cloudflare_vless_trojan/assets/136957005/24580588-d8cb-4804-818e-35888876f047)
![屏幕截图 2024-05-19 175007](https://github.com/yonggekkk/Cloudflare_vless_trojan/assets/136957005/bbf1f987-05a0-46e0-9de3-0d5a29ac1a2d)

**Comment by yonggekkk** [comment]
用官方IP

**Comment by iweec** [comment]
![屏幕截图 2024-05-25 152911](https://github.com/yonggekkk/Cloudflare_vless_trojan/assets/136957005/9cbe4811-d70d-4f55-9222-358fb9052590)
使用官方IP仍然如此

**Comment by yonggekkk** [comment]
那可能是本地环境问题了。。。。
