### ISSUE TITLE
补充一下

### ISSUE THREAD

**Issue by yray680** [yonggekkk/Cloudflare_vless_trojan#89]
要在 Cloudflare Workers 上部署这个脚本,你需要:

1. 登录 Cloudflare 控制台并创建一个新的 Worker。
2. 将上述代码复制粘贴到 Worker 编辑器中。
3. 保存并部署 Worker。

对于 Cloudflare Pages,你可以在 `pages/api` 目录下创建一个 API 路由,并在其中实现类似的代理逻辑。这样就可以在 Cloudflare Pages 上部署一个代理服务。

需要注意的是,使用代理脚本可能会涉及一些安全和隐私问题,例如跨站脚本攻击和信息泄露。因此在实际使用时,你需要考虑这些因素并采取相应的安全措施。

**Comment by yonggekkk** [comment]
说得很官方嘛
