### ISSUE TITLE
不稳定，频繁出现EOF错误或超时

### ISSUE THREAD

**Issue by GITSOP** [yonggekkk/Cloudflare_vless_trojan#91]
6月3号后在客户端（v2RayN和v2RayNG）中开启分片功能后仍然频繁出现EOF错误和tls连接超时，有可能被GFW识别，但不知道什么原因没有被直接阻断而是连接不稳定，希望有解决方案。

**Comment by yonggekkk** [comment]
我这使用一切正常。。关TLS试试

**Comment by tatorhan** [comment]
我移动和电信的网络发现，很多网站都不能访问。例如cf或chatgpt

**Comment by yonggekkk** [comment]
> 我移动和电信的网络发现，很多网站都不能访问。例如cf或chatgpt

换个优选地址

**Comment by xzlosats111** [comment]
能连接其他网站说明书本身大概率不是墙的锅，有可能是反代优选域名炸了，chatgpt还有一种可能是运气不好，刚好选到香港的反代地址，直接被屏蔽了，连接断开重连一下，刷新到别的地方的地址就行了
另外本地这边地址我之前是出现过shopify这个地址解析出来的IP开不了tls的情况，原因未知，玄学，一度也让我以为被屏蔽了，后来发现是换个地址就行了

**Comment by wanghaisheng** [comment]
@xzlosats111  请教一下 链接以后显示 日本Ip,但苹果手机的tiktokapp 会一直报链接不稳定  分片也是按照教程开的，优选域名这些我没有动 用的github worker.js里面默认的

**Comment by xzlosats111** [comment]
我去怎么给你路由到日本去了，你用的是www.visa.com.sg这个默认域名吗，这个域名我暂时没有eof问题，目前这个问题应该还是ip的问题，我电信wto.org最近会路由到香港，可能线路质量不行，还不如去美国呢
但是现在这玩意太热门了，大厂域名解析出来的ip有明显的晚高峰现象，建议用https://github.com/XIU2/CloudflareSpeedTest这个项目优选一个官方ip填进去，选反代ip也可以，但是容易挂
