### ISSUE TITLE
请教一下tls分片这个技术的细节

### ISSUE THREAD

**Issue by xzlosats111** [yonggekkk/Cloudflare_vless_trojan#94]
就这个技术我目前没有看到详细的介绍，不是很能理解 
就这个技术是为了clienthello包被切到不同的TCP包中吗，和TCP自带的mtu切片有什么区别吗，是利用tls的特性还是tcp的特性呢，如果只是简单把clienthello包分割到不同tcp包中，那墙根据TCP包序列号重建TCP包应该也算是比较老的技术了吧，clienthello明文文重建完不就又被找到被拦截了，就这个重建过程的开销是否会大到墙无法接受呢？毕竟workers翻墙这个项目已经热门到墙总该采取点行动了吧，为何tls分片这个功能对抗sni阻断效果如此立竿见影 
还是利用了什么tls别的特性呢，但总得有点类似序列号之类的东西，服务端才能重建包吧，凭啥一个明文信息只有服务端能获取墙不能获取呢？ 
另外墙能否根据当年搞ech那样发现一个连接sni信息无法获取直接丢包呢，tls分片这个东西有能作为墙过滤的流量特征吗？
 毕竟这个功能对于workers这个项目能不能玩下去还是一个重要因素的，关tls墙不拦截只是墙不想拦截和拦截不了还是有本质区别的，所以想多了解一点儿，甬哥能帮忙解答一下吗？

**Comment by yonggekkk** [comment]
具体去xray官方文档看下分片原理吧！伊朗那边用得比较多

**Comment by xzlosats111** [comment]
官方文档似乎是查不到相关介绍的
在xray的issue里面倒是有看到相关讨论的
https://github.com/XTLS/Xray-core/issues/1996 
似乎还就是暴力切片顶多有一点混淆让墙无力检测放过去，如果这么简单墙居然至今为止没什么反制措施
https://github.com/XTLS/Xray-core/pull/2181/files 
这个是这部分功能的源码，我不会看，能帮忙看一下吗

另外使用vmess协议搭建是有什么困难还是意义不大吗，为什么这么久了没有看到有人去实现

**Comment by yonggekkk** [comment]
原理方面也没深研。。至于VMESS，好像还是半成品
