### ISSUE TITLE
伪装网页失效了。

### ISSUE THREAD

**Issue by jiojiojackson** [yonggekkk/Cloudflare_vless_trojan#95]
填写了伪装域名。访问显示以下内容，不能显示伪装网站。求解决。
{
    "clientTcpRtt": 80,
    "longitude": "121.00000",
    "httpProtocol": "HTTP/2",
    "tlsCipher": "AEAD-AES128-GCM-SHA256",
    "continent": "AS",
    "asn": 131642,
    "clientAcceptEncoding": "gzip, deflate, br, zstd",
    "country": "TW",
    "tlsClientAuth": {
        "certIssuerDNLegacy": "",
        "certIssuerSKI": "",
        "certSubjectDNRFC2253": "",
        "certSubjectDNLegacy": "",
        "certFingerprintSHA256": "",
        "certNotBefore": "",
        "certSKI": "",
        "certSerial": "",
        "certIssuerDN": "",
        "certVerified": "NONE",
        "certNotAfter": "",
        "certSubjectDN": "",
        "certPresented": "0",
        "certRevoked": "0",
        "certIssuerSerial": "",
        "certIssuerDNRFC2253": "",
        "certFingerprintSHA1": ""
    },
    "tlsExportedAuthenticator": {
        "clientFinished": "2240788483f352b6373c7ad09cb6e2dabbda108d79e0c75cf083e1b5c47241b5",
        "clientHandshake": "2aa1729ece9005b1571555fc8e0f9bf20a918ac3d9c3f826027b88d8b91ef22c",
        "serverHandshake": "07e23a5bbb3041e8765147802cdfcc56bd3fe4d33fbba640b33bfb1789653e45",
        "serverFinished": "6b813697a41a2fd396215f8b544c4e16d3a764070ee678c0d8e02a695f36e5be"
    },
    "tlsVersion": "TLSv1.3",
    "colo": "HKG",
    "timezone": "Asia/Taipei",
    "verifiedBotCategory": "",
    "edgeRequestKeepAliveStatus": 1,
    "tlsClientRandom": "nJlcdC/ThYatodTK9XXHTDMgntjEiBc7WPLGz9x0/m0=",
    "tlsClientExtensionsSha1": "0l2sbQ1E65zNRORrUHTUFKpn+zY=",
    "tlsClientHelloLength": "2003",
    "asOrganization": "Pittqiao Network Information Co.",
    "requestPriority": "weight=256;exclusive=1",
    "latitude": "24.00000",
    "botManagement": {
        "corporateProxy": false,
        "verifiedBot": false,
        "jsDetection": {
            "passed": false
        },
        "staticResource": false,
        "detectionIds": {},
        "score": 99
    }
}

**Comment by yonggekkk** [comment]
按项目说明重设下

**Comment by jiojiojackson** [comment]
可修改Vless_workers_pages文件下的_worker.js文件
1、UUID必须自定义（第7行）

2、如果无法访问CF类网站或者ChatGPT，说明ProxyIP失效，可更换ProxyIP，自定义（第9行）

3、伪装网页默认留空，显示为本地IP信息代码界面，可自定义（第10行）

我已经按照以上项目说明重设了，还是一样。可以帮我看看配置对吗？我复制了worker的前面几行代码
// version base on commit 43fad05dcdae3b723c53c226f8181fc5bd47223e, time is 2023-06-22 15:20:02 UTC.
// @ts-ignore
import { connect } from "cloudflare:sockets";

// How to generate your own UUID:
// [Windows] Press "Win + R", input cmd and run:  Powershell -NoExit -Command "[guid]::NewGuid()"
let userID = "b38e472a-255e-4769-8273-c2a4b97f0a69";

const proxyIPs = ["126.70.175.136"]; //workers.cloudflare.cyou bestproxy.onecf.eu.org cdn-all.xn--b6gac.eu.org cdn.xn--b6gac.eu.org
const cn_hostnames = ["tv.cctv.cn"];

let proxyIP = proxyIPs[Math.floor(Math.random() * proxyIPs.length)];

if (!isValidUUID(userID)) {
  throw new Error("uuid is not valid");
}

**Comment by yonggekkk** [comment]
> 可修改Vless_workers_pages文件下的_worker.js文件 1、UUID必须自定义（第7行）
> 
> 2、如果无法访问CF类网站或者ChatGPT，说明ProxyIP失效，可更换ProxyIP，自定义（第9行）
> 
> 3、伪装网页默认留空，显示为本地IP信息代码界面，可自定义（第10行）
> 
> 我已经按照以上项目说明重设了，还是一样。可以帮我看看配置对吗？我复制了worker的前面几行代码 // version base on commit 43fad05dcdae3b723c53c226f8181fc5bd47223e, time is 2023-06-22 15:20:02 UTC. // @ts-ignore import { connect } from "cloudflare:sockets";
> 
> // How to generate your own UUID: // [Windows] Press "Win + R", input cmd and run: Powershell -NoExit -Command "[guid]::NewGuid()" let userID = "b38e472a-255e-4769-8273-c2a4b97f0a69";
> 
> const proxyIPs = ["126.70.175.136"]; //workers.cloudflare.cyou bestproxy.onecf.eu.org cdn-all.xn--b6gac.eu.org cdn.xn--b6gac.eu.org const cn_hostnames = ["tv.cctv.cn"];
> 
> let proxyIP = proxyIPs[Math.floor(Math.random() * proxyIPs.length)];
> 
> if (!isValidUUID(userID)) { throw new Error("uuid is not valid"); }

已修正，你再重新复制代码试试

**Comment by jiojiojackson** [comment]
现在可以了.谢谢
