### ISSUE TITLE
苹果手机无法使用chatgpt

### ISSUE THREAD

**Issue by jiojiojackson** [yonggekkk/Cloudflare_vless_trojan#98]
配置了反代ip后，电脑可以使用chatgpt，小火箭开了全局代理，还是无法使用chatgpt。请问大佬应该如何解决？

**Comment by yonggekkk** [comment]
只能自己找个proxyip，现在大多数只能网页gpt

**Comment by jiojiojackson** [comment]
请问可以介绍一下找反代ip 的方法吗？用您项目的那个找反代ip 的脚本，找出的ip 只能在电脑使用。

**Comment by yonggekkk** [comment]
反代IP网上一大堆，只是死得快，要经常换

**Comment by jiojiojackson** [comment]
大佬可以做个定期更新的反代ip 共享吗？适用于手机的

**Comment by yonggekkk** [comment]
很多大佬已经在做了，脚本代码里的proxyip也收录几个大佬分享的反代域名。你可以使用

**Comment by jiojiojackson** [comment]
可以分享一些这些大佬的链接吗？没找到，谢谢🙏

**Comment by yonggekkk** [comment]
项目有写
